dist: precise
language: python
sudo: false

python:
  - "2.7.9"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy"
  - "pypy3"
  
matrix:
  fast_finish: true
  allow_failures:
    - python: "3.7-dev"
      # 3.7-dev started crashing when building lxml although the neither the python version nor the lxml version seemed to change.
      # Will have to investigate further.
    - python: "pypy"
    - python: "pypy3"
      # pypy will just crash due to an incompatibility with lxml.
      # Newer versions of pypy seem to crash also, so we probably have to fix with a newer version of lxml

  
install:
 - pip install unittest2
 - pip install nose
 - pip install pyxb==1.2.5
 - pip install lxml==3.7.3
 - pip install coveralls==1.1

before_script:
  - git submodule update --remote --recursive

script:
 - nosetests --with-coverage -cover-package=authorizenet
 - coveralls
 - python setup.py install
 - cd sample-code-python
 - python ./test-runner.py
